"""Coverage and error-path tests for :mod:`koopman_graph.graph_utils`."""

from __future__ import annotations

import sys
from unittest.mock import MagicMock, patch

import pytest
import torch

from koopman_graph.graph_utils import (
    IsotypicDecomposition,
    compute_isotypic_decomposition,
)
from koopman_graph.graph_utils.representation import (
    _MAX_ENUMERATED_GROUP_ORDER,
    _PROJ_ATOL,
    _enumerate_group,
)


def _assert_projector_algebra(report: IsotypicDecomposition) -> None:
    """Idempotence, orthogonality, and partition of identity."""
    eye = torch.eye(report.num_nodes, dtype=torch.float64)
    total = torch.zeros_like(eye)
    for i, left in enumerate(report.projectors):
        assert float(torch.linalg.norm(left @ left - left)) <= _PROJ_ATOL
        total = total + left
        for j, right in enumerate(report.projectors):
            if i >= j:
                continue
            assert float(torch.linalg.norm(left @ right)) <= _PROJ_ATOL
    assert float(torch.linalg.norm(total - eye)) <= _PROJ_ATOL


def test_isotypic_input_guards() -> None:
    """Public API rejects non-positive N, bad edge shapes, and OOB edges."""
    from koopman_graph.graph_utils.representation import _adjacency_dict

    empty = torch.empty((2, 0), dtype=torch.long)
    with pytest.raises(ValueError, match="num_nodes must be positive"):
        compute_isotypic_decomposition(empty, 0)
    with pytest.raises(ValueError, match=r"edge_index must have shape \(2, E\)"):
        compute_isotypic_decomposition(torch.zeros(3, 3), 3)
    # OOB is validated in ``_adjacency_dict`` (after pynauty import in the
    # public path); exercise the helper directly so CI without pynauty still
    # covers the branch.
    edges = torch.tensor(
        [[0, 1, 1, 2, 2, 3, 0], [1, 0, 2, 1, 3, 2, 9]],
        dtype=torch.long,
    )
    with pytest.raises(ValueError, match=r"outside \[0, 3\]"):
        _adjacency_dict(edges, 4)


def test_isotypic_single_node_symmetric_group() -> None:
    """N=1 uses the closed-form S_n shortcut without pynauty."""
    report = compute_isotypic_decomposition(
        torch.empty((2, 0), dtype=torch.long),
        1,
    )
    assert report.dimensions == (1,)
    assert report.group_order == 1
    _assert_projector_algebra(report)


def test_isotypic_mock_pynauty_path_graph() -> None:
    """Non-S_n graphs exercise generators → enumerate → orbital projectors."""
    # Path 0—1—2; Aut = Z2 generated by the reflection (0 ↔ 2).
    edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]], dtype=torch.long)
    mock_pynauty = MagicMock()
    mock_pynauty.Graph.return_value = MagicMock()
    mock_pynauty.autgrp.return_value = ([(2, 1, 0)], 2.0, 0.0, [0, 1, 0], 2)
    del mock_pynauty.autgroup

    with patch.dict(sys.modules, {"pynauty": mock_pynauty}):
        report = compute_isotypic_decomposition(edge_index, 3)

    assert report.method == "automorphism"
    assert report.group_order == 2
    assert sum(report.dimensions) == 3
    _assert_projector_algebra(report)
    assert mock_pynauty.autgrp.call_count == 1


def test_isotypic_group_order_ceiling() -> None:
    """Reported |Aut(G)| above the enumeration ceiling is refused."""
    edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]], dtype=torch.long)
    mock_pynauty = MagicMock()
    mock_pynauty.Graph.return_value = MagicMock()
    mock_pynauty.autgrp.return_value = (
        [],
        float(_MAX_ENUMERATED_GROUP_ORDER + 1),
        0.0,
        [0, 1, 2],
        3,
    )
    del mock_pynauty.autgroup

    with (
        patch.dict(sys.modules, {"pynauty": mock_pynauty}),
        pytest.raises(ValueError, match="enumeration ceiling"),
    ):
        compute_isotypic_decomposition(edge_index, 3)


def test_isotypic_enumeration_order_mismatch() -> None:
    """Empty generators with claimed |G|>1 raise RuntimeError."""
    edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]], dtype=torch.long)
    mock_pynauty = MagicMock()
    mock_pynauty.Graph.return_value = MagicMock()
    mock_pynauty.autgrp.return_value = ([], 2.0, 0.0, [0, 1, 2], 3)
    del mock_pynauty.autgroup

    with (
        patch.dict(sys.modules, {"pynauty": mock_pynauty}),
        pytest.raises(RuntimeError, match="enumerated \\|Aut"),
    ):
        compute_isotypic_decomposition(edge_index, 3)


def test_enumerate_group_exceeds_max_order() -> None:
    """BFS enumeration stops when |seen| exceeds max_order."""
    # Generators of S_3; identity-only ceiling of 1 must trip.
    with pytest.raises(ValueError, match="exceeded max_order"):
        _enumerate_group([(1, 0, 2), (0, 2, 1)], 3, max_order=1)
