"""Patch-coverage guards for the 0.11.0 Codecov patch gate (target ≥ 90%)."""

from __future__ import annotations

import sys
from types import SimpleNamespace
from unittest.mock import MagicMock, patch

import pytest
import torch
from torch_geometric.data import Data

from koopman_graph import GNNDecoder, GNNEncoder, GraphKoopmanModel
from koopman_graph.baselines.gnn.stgode import STGODEBaseline, _GraphODEFunc
from koopman_graph.baselines.graph_vamp import GraphVAMPBaseline
from koopman_graph.data import GraphSnapshotSequence
from koopman_graph.datasets.molecular import contact_edge_index
from koopman_graph.graph_utils import (
    IsotypicDecomposition,
    compute_isotypic_decomposition,
)
from koopman_graph.graph_utils.representation import (
    _MAX_ENUMERATED_GROUP_ORDER,
    _PROJ_ATOL,
    _enumerate_group,
)
from koopman_graph.hierarchical import HierarchicalGraphKoopmanModel
from koopman_graph.nn.cell_complex import (
    CellComplex,
    CellComplexConv,
    build_cell_complex_convs,
    hodge_laplacian_matvec,
)
from koopman_graph.operators import HypergraphKoopmanOperator


def _assert_projector_algebra(report: IsotypicDecomposition) -> None:
    """Idempotence, orthogonality, and partition of identity."""
    eye = torch.eye(report.num_nodes, dtype=torch.float64)
    total = torch.zeros_like(eye)
    for i, left in enumerate(report.projectors):
        assert float(torch.linalg.norm(left @ left - left)) <= _PROJ_ATOL
        total = total + left
        for j, right in enumerate(report.projectors):
            if i >= j:
                continue
            assert float(torch.linalg.norm(left @ right)) <= _PROJ_ATOL
    assert float(torch.linalg.norm(total - eye)) <= _PROJ_ATOL


def _tiny_sequence() -> GraphSnapshotSequence:
    edge = torch.tensor([[0, 1], [1, 0]], dtype=torch.long)
    return GraphSnapshotSequence(
        [Data(x=torch.ones(2, 3) * (0.9**t), edge_index=edge) for t in range(6)]
    )


def _tiny_model(*, seed: int = 0) -> GraphKoopmanModel:
    torch.manual_seed(seed)
    return GraphKoopmanModel(
        encoder=GNNEncoder(3, 8, 4, num_layers=1),
        decoder=GNNDecoder(4, 8, 3, num_layers=1),
        latent_dim=4,
        time_step=0.1,
    )


# ---------------------------------------------------------------------------
# hierarchical / evaluate_forecast call-site parity
# ---------------------------------------------------------------------------


def test_hierarchical_predict_rejects_future_presence() -> None:
    """Presence-mask kwargs are accepted for parity but must stay None."""
    hier = HierarchicalGraphKoopmanModel(_tiny_model(), pool_ratios=(0.5,))
    sequence = _tiny_sequence()
    preds = hier.predict(sequence[0], steps=1, future_presence=None)
    assert len(preds) == 1
    with pytest.raises(ValueError, match="does not support future_presence"):
        hier.predict(
            sequence[0],
            steps=1,
            future_presence=torch.ones(1, sequence.num_nodes, dtype=torch.bool),
        )


# ---------------------------------------------------------------------------
# graph_utils.representation (mock pynauty path)
# ---------------------------------------------------------------------------


def test_isotypic_input_guards() -> None:
    """Public API rejects non-positive N, bad edge shapes, and OOB edges."""
    from koopman_graph.graph_utils.representation import _adjacency_dict

    empty = torch.empty((2, 0), dtype=torch.long)
    with pytest.raises(ValueError, match="num_nodes must be positive"):
        compute_isotypic_decomposition(empty, 0)
    with pytest.raises(ValueError, match=r"edge_index must have shape \(2, E\)"):
        compute_isotypic_decomposition(torch.zeros(3, 3), 3)
    # OOB is validated in ``_adjacency_dict`` (after pynauty import in the
    # public path); exercise the helper directly so CI without pynauty still
    # covers the branch.
    edges = torch.tensor(
        [[0, 1, 1, 2, 2, 3, 0], [1, 0, 2, 1, 3, 2, 9]],
        dtype=torch.long,
    )
    with pytest.raises(ValueError, match=r"outside \[0, 3\]"):
        _adjacency_dict(edges, 4)


def test_isotypic_single_node_symmetric_group() -> None:
    """N=1 uses the closed-form S_n shortcut without pynauty."""
    report = compute_isotypic_decomposition(
        torch.empty((2, 0), dtype=torch.long),
        1,
    )
    assert report.dimensions == (1,)
    assert report.group_order == 1
    _assert_projector_algebra(report)


def test_isotypic_mock_pynauty_path_graph() -> None:
    """Non-S_n graphs exercise generators → enumerate → orbital projectors."""
    # Path 0—1—2; Aut = Z2 generated by the reflection (0 ↔ 2).
    edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]], dtype=torch.long)
    mock_pynauty = MagicMock()
    mock_pynauty.Graph.return_value = MagicMock()
    mock_pynauty.autgrp.return_value = ([(2, 1, 0)], 2.0, 0.0, [0, 1, 0], 2)
    del mock_pynauty.autgroup

    with patch.dict(sys.modules, {"pynauty": mock_pynauty}):
        report = compute_isotypic_decomposition(edge_index, 3)

    assert report.method == "automorphism"
    assert report.group_order == 2
    assert sum(report.dimensions) == 3
    _assert_projector_algebra(report)
    assert mock_pynauty.autgrp.call_count == 1


def test_isotypic_group_order_ceiling() -> None:
    """Reported |Aut(G)| above the enumeration ceiling is refused."""
    edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]], dtype=torch.long)
    mock_pynauty = MagicMock()
    mock_pynauty.Graph.return_value = MagicMock()
    mock_pynauty.autgrp.return_value = (
        [],
        float(_MAX_ENUMERATED_GROUP_ORDER + 1),
        0.0,
        [0, 1, 2],
        3,
    )
    del mock_pynauty.autgroup

    with (
        patch.dict(sys.modules, {"pynauty": mock_pynauty}),
        pytest.raises(ValueError, match="enumeration ceiling"),
    ):
        compute_isotypic_decomposition(edge_index, 3)


def test_isotypic_enumeration_order_mismatch() -> None:
    """Empty generators with claimed |G|>1 raise RuntimeError."""
    edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]], dtype=torch.long)
    mock_pynauty = MagicMock()
    mock_pynauty.Graph.return_value = MagicMock()
    mock_pynauty.autgrp.return_value = ([], 2.0, 0.0, [0, 1, 2], 3)
    del mock_pynauty.autgroup

    with (
        patch.dict(sys.modules, {"pynauty": mock_pynauty}),
        pytest.raises(RuntimeError, match="enumerated \\|Aut"),
    ):
        compute_isotypic_decomposition(edge_index, 3)


def test_enumerate_group_exceeds_max_order() -> None:
    """BFS enumeration stops when |seen| exceeds max_order."""
    # Generators of S_3; identity-only ceiling of 1 must trip.
    with pytest.raises(ValueError, match="exceeded max_order"):
        _enumerate_group([(1, 0, 2), (0, 2, 1)], 3, max_order=1)


# ---------------------------------------------------------------------------
# distributed.ray_train
# ---------------------------------------------------------------------------


def test_ray_train_rejects_val_monitor_without_val_sequences() -> None:
    """early_stopping_monitor='val' requires val_sequences."""
    pytest.importorskip("ray.train")
    from koopman_graph.distributed.ray_train import run_ray_train_fit_loop

    with pytest.raises(ValueError, match="requires val_sequences"):
        run_ray_train_fit_loop(
            _tiny_model(),
            [_tiny_sequence()],
            epochs=1,
            num_workers=1,
            early_stopping_monitor="val",
        )


def _patch_ray_trainer(fake_trainer: MagicMock):
    """Patch ``ray.train.torch.TorchTrainer`` while keeping other Ray imports."""
    from koopman_graph.distributed import ray_train as ray_train_mod

    real_import_module = ray_train_mod.importlib.import_module

    def _import_module(name: str, package: str | None = None) -> object:
        if name == "ray.train.torch":
            mod = MagicMock()
            mod.TorchTrainer = MagicMock(return_value=fake_trainer)
            return mod
        return real_import_module(name, package)

    return patch.object(
        ray_train_mod.importlib,
        "import_module",
        side_effect=_import_module,
    )


def test_ray_train_raises_when_checkpoint_missing() -> None:
    """Missing result.checkpoint surfaces a RuntimeError."""
    pytest.importorskip("ray.train")
    from koopman_graph.distributed.ray_train import run_ray_train_fit_loop

    fake_result = SimpleNamespace(error=None, checkpoint=None)
    fake_trainer = MagicMock()
    fake_trainer.fit.return_value = fake_result

    with (
        _patch_ray_trainer(fake_trainer),
        pytest.raises(RuntimeError, match="without a result checkpoint"),
    ):
        run_ray_train_fit_loop(
            _tiny_model(),
            [_tiny_sequence()],
            epochs=1,
            num_workers=1,
        )


def test_ray_train_propagates_trainer_error() -> None:
    """result.error is re-raised from the driver."""
    pytest.importorskip("ray.train")
    from koopman_graph.distributed.ray_train import run_ray_train_fit_loop

    boom = RuntimeError("boom")
    fake_result = SimpleNamespace(error=boom, checkpoint=MagicMock())
    fake_trainer = MagicMock()
    fake_trainer.fit.return_value = fake_result

    with (
        _patch_ray_trainer(fake_trainer),
        pytest.raises(RuntimeError, match="boom"),
    ):
        run_ray_train_fit_loop(
            _tiny_model(),
            [_tiny_sequence()],
            epochs=1,
            num_workers=1,
        )


def test_ray_train_window_sampler_path() -> None:
    """windows_per_epoch exercises the window-sampler branch in the worker."""
    pytest.importorskip("ray.train")
    from koopman_graph.distributed import run_ray_train_fit_loop

    history = run_ray_train_fit_loop(
        _tiny_model(),
        [_tiny_sequence()],
        epochs=1,
        num_workers=1,
        window_length=3,
        windows_per_epoch=2,
        batch_size=1,
        window_seed=0,
    )
    assert history.epochs == 1
    assert len(history.loss) == 1


# ---------------------------------------------------------------------------
# baselines.gnn.stgode
# ---------------------------------------------------------------------------


def test_stgode_constructor_and_ode_guards() -> None:
    """Constructor / ODE-func / history-shape validation branches."""
    with pytest.raises(ValueError, match="num_layers must be positive"):
        STGODEBaseline(1, 4, 1, num_layers=0)
    with pytest.raises(ValueError, match="integration_time must be positive"):
        STGODEBaseline(1, 4, 1, integration_time=0.0)
    with pytest.raises(ValueError, match="solver_rtol and solver_atol"):
        STGODEBaseline(1, 4, 1, solver_rtol=0.0)

    ode = _GraphODEFunc(2)
    with pytest.raises(RuntimeError, match="adjacency must be set"):
        ode.forward(torch.tensor(0.0), torch.zeros(1, 3, 2))

    pytest.importorskip("torchdiffeq")
    model = STGODEBaseline(1, 4, 1, history_len=2, num_layers=1)
    edge = torch.tensor([[0, 1], [1, 0]], dtype=torch.long)
    with pytest.raises(ValueError, match="history must have shape"):
        model.predict_next(torch.randn(2, 1), edge, None)


# ---------------------------------------------------------------------------
# baselines.graph_vamp
# ---------------------------------------------------------------------------


def test_graph_vamp_fit_and_score_guards() -> None:
    """Fit/score edge-resolution and lag/epochs validation."""
    edge = torch.tensor([[0, 1], [1, 0]], dtype=torch.long)
    snaps = [Data(x=torch.randn(2, 3), edge_index=edge) for _ in range(4)]
    model = GraphVAMPBaseline(in_channels=3, hidden_channels=4, latent_dim=2)

    with pytest.raises(ValueError, match="at least one snapshot"):
        model.fit([])
    with pytest.raises(ValueError, match="lag must be >= 1"):
        model.fit(snaps, lag=0)
    with pytest.raises(ValueError, match="num_timesteps > lag"):
        model.fit(snaps, lag=4)
    with pytest.raises(ValueError, match="epochs must be >= 1"):
        model.fit(snaps, epochs=0)
    with pytest.raises(ValueError, match="either edge_index or positions_nm"):
        model.fit(snaps, edge_index=edge, positions_nm=torch.zeros(2, 3))
    with pytest.raises(ValueError, match="positions_nm is required"):
        model.fit(snaps, cutoff_nm=0.5)
    with pytest.raises(ValueError, match="cutoff_nm is required"):
        model.fit(snaps, positions_nm=torch.zeros(2, 3))

    from koopman_graph.baselines.graph_vamp import _resolve_fit_edges

    traj = MagicMock()
    traj.__getitem__.return_value = Data(x=torch.randn(2, 3))
    with pytest.raises(ValueError, match="could not resolve contact edges"):
        _resolve_fit_edges(
            traj,
            edge_index=None,
            positions_nm=None,
            cutoff_nm=None,
        )

    with pytest.raises(RuntimeError, match="score requires a prior fit"):
        model.score(snaps)

    encoded = model.encode_frame(snaps[0])
    assert encoded.shape == (2,)


# ---------------------------------------------------------------------------
# interop.deeptime
# ---------------------------------------------------------------------------


def test_deeptime_feature_edge_cases() -> None:
    """Integer coercion, empty matrices, and unrecognized payloads."""
    pytest.importorskip("deeptime")
    import numpy as np

    from koopman_graph.interop.deeptime import (
        trajectory_features_from_deeptime,
        trajectory_features_to_deeptime,
    )

    features = np.arange(12, dtype=np.int64).reshape(6, 2)
    dataset = trajectory_features_to_deeptime(features, lag=1)
    recovered = trajectory_features_from_deeptime(dataset)
    assert recovered.dtype == np.float64
    assert np.allclose(recovered, features.astype(np.float64))

    with pytest.raises(ValueError, match="non-empty in both dimensions"):
        trajectory_features_to_deeptime(np.zeros((0, 3)), lag=1)
    with pytest.raises(ValueError, match="non-empty in both dimensions"):
        trajectory_features_to_deeptime(np.zeros((5, 0)), lag=1)
    with pytest.raises(ValueError, match="expected a deeptime"):
        trajectory_features_from_deeptime(object())


# ---------------------------------------------------------------------------
# nn.cell_complex
# ---------------------------------------------------------------------------


def test_cell_complex_validation_and_residual() -> None:
    """Construction guards, matvec shapes, residual skip, single-layer stack."""
    with pytest.raises(ValueError, match="num_nodes must be >= 1"):
        CellComplex(
            num_nodes=0,
            edge_index=torch.empty((2, 0), dtype=torch.long),
            face_index=torch.empty((3, 0), dtype=torch.long),
        )
    with pytest.raises(ValueError, match=r"edge_index must have shape \(2"):
        CellComplex(
            num_nodes=3,
            edge_index=torch.zeros(3, 3),
            face_index=torch.empty((3, 0), dtype=torch.long),
        )
    with pytest.raises(ValueError, match=r"lie in \[0, 2\)"):
        CellComplex(
            num_nodes=2,
            edge_index=torch.tensor([[0], [5]], dtype=torch.long),
            face_index=torch.empty((3, 0), dtype=torch.long),
        )

    complex_ = CellComplex(
        num_nodes=3,
        edge_index=torch.tensor([[0, 1, 0], [1, 2, 2]], dtype=torch.long),
        face_index=torch.tensor([[0], [1], [2]], dtype=torch.long),
    )
    with pytest.raises(ValueError, match="1D or 2D"):
        hodge_laplacian_matvec(complex_, 0, torch.zeros(3, 3, 1))
    with pytest.raises(ValueError, match="leading dim"):
        hodge_laplacian_matvec(complex_, 0, torch.zeros(4, 1))

    conv = CellComplexConv(4, 4, residual=True)
    x = torch.randn(3, 4)
    out = conv(x, complex_.edge_index)
    assert out.shape == (3, 4)

    layers = build_cell_complex_convs(2, 4, 3, num_layers=1)
    assert len(layers) == 1


# ---------------------------------------------------------------------------
# operators.hypergraph
# ---------------------------------------------------------------------------


def test_hypergraph_dual_and_effective_matrix_guards() -> None:
    """K_bwd / effective_matrix conflict paths on Zhou vs dual modes."""
    zhou = HypergraphKoopmanOperator(
        2,
        init_mode="identity",
        incidence_mode="zhou_symmetric",
    )
    with pytest.raises(RuntimeError, match="K_bwd is only available"):
        _ = zhou.K_bwd
    with pytest.raises(ValueError, match="k_bwd is only valid"):
        zhou.set_dense_matrices(
            torch.eye(2),
            torch.zeros(2, 2),
            k_bwd=torch.eye(2),
        )

    dual = HypergraphKoopmanOperator(
        2,
        init_mode="identity",
        incidence_mode="dual_random_walk",
    )
    # Single hyperarc 0 → {1, 2} (bipartite incidence; see directed tests).
    tail = torch.tensor([[0], [0]], dtype=torch.long)
    head = torch.tensor([[1, 2], [0, 0]], dtype=torch.long)
    with pytest.raises(ValueError, match="at most one of k_self"):
        dual.effective_matrix(
            None,
            3,
            tail_index=tail,
            head_index=head,
            k_self=torch.eye(2),
            k_self_blocks=torch.eye(2).unsqueeze(0).repeat(3, 1, 1),
        )
    matrix = dual.effective_matrix(None, 3, tail_index=tail, head_index=head)
    assert matrix.shape == (6, 6)
    spec = dual.spectrum(None, 3, tail_index=tail, head_index=head)
    assert spec.eigenvalues.numel() == 6


# ---------------------------------------------------------------------------
# datasets.molecular.contact_graph / secondary guards
# ---------------------------------------------------------------------------


def test_contact_edge_index_rejects_nonfinite() -> None:
    """Non-finite coordinates fail position validation."""
    positions = torch.tensor([[0.0, 0.0, 0.0], [float("nan"), 0.0, 0.0]])
    with pytest.raises(ValueError, match="positions_nm must be finite"):
        contact_edge_index(positions, cutoff_nm=0.5)


# ---------------------------------------------------------------------------
# observables (coerce_face_index + sheaf Laplacian matvecs)
# ---------------------------------------------------------------------------


def test_coerce_face_index_and_sheaf_matvec_guards() -> None:
    """Face-index and sheaf Laplacian MVP validation branches."""
    from koopman_graph.observables import (
        coerce_face_index,
        diagonal_sheaf_laplacian_matvec,
        general_sheaf_laplacian_matvec,
    )

    with pytest.raises(ValueError, match="num_nodes must be >= 1"):
        coerce_face_index(torch.empty((3, 0), dtype=torch.long), num_nodes=0)
    with pytest.raises(ValueError, match=r"face_index must have shape \(3"):
        coerce_face_index(torch.zeros(2, 1, dtype=torch.long), num_nodes=2)
    with pytest.raises(ValueError, match="integer tensor"):
        coerce_face_index(torch.zeros(3, 1), num_nodes=2)
    with pytest.raises(ValueError, match=r"lie in \[0, 2\)"):
        coerce_face_index(
            torch.tensor([[0], [1], [9]], dtype=torch.long),
            num_nodes=2,
        )
    empty = coerce_face_index(torch.empty((3, 0), dtype=torch.long), num_nodes=2)
    assert empty.shape == (3, 0) and empty.dtype == torch.long

    edge = torch.tensor([[0, 1], [1, 0]], dtype=torch.long)
    x = torch.randn(2, 3)
    with pytest.raises(ValueError, match="x must be 2D"):
        diagonal_sheaf_laplacian_matvec(
            edge, torch.randn(2), torch.ones(3), torch.ones(3)
        )
    with pytest.raises(ValueError, match="source_diag/target_diag"):
        diagonal_sheaf_laplacian_matvec(edge, x, torch.ones(2), torch.ones(3))
    with pytest.raises(ValueError, match="num_nodes="):
        diagonal_sheaf_laplacian_matvec(
            edge, x, torch.ones(3), torch.ones(3), num_nodes=5
        )
    with pytest.raises(ValueError, match=r"edge_index must have shape \(2"):
        diagonal_sheaf_laplacian_matvec(
            torch.zeros(3, 2), x, torch.ones(3), torch.ones(3)
        )

    eye = torch.eye(3)
    with pytest.raises(ValueError, match="x must be 2D"):
        general_sheaf_laplacian_matvec(edge, torch.randn(2), eye, eye)
    with pytest.raises(ValueError, match="source_map/target_map"):
        general_sheaf_laplacian_matvec(edge, x, torch.ones(3), eye)
    with pytest.raises(ValueError, match="num_nodes="):
        general_sheaf_laplacian_matvec(edge, x, eye, eye, num_nodes=4)
    with pytest.raises(ValueError, match=r"edge_index must have shape \(2"):
        general_sheaf_laplacian_matvec(torch.zeros(1, 2), x, eye, eye)


# ---------------------------------------------------------------------------
# operators.orbit_ties
# ---------------------------------------------------------------------------


def test_orbit_ties_isotypic_config_and_binding_guards() -> None:
    """Isotypic flag conflicts and unbound / missing-topology bind errors."""
    from koopman_graph.operators import GraphKoopmanOperator

    with pytest.raises(ValueError, match="mutually exclusive with an explicit"):
        GraphKoopmanOperator(
            2,
            init_mode="identity",
            isotypic_symmetry=True,
            orbit_partition=((0, 1),),
        )
    with pytest.raises(ValueError, match="mutually exclusive with auto_orbits"):
        GraphKoopmanOperator(
            2,
            init_mode="identity",
            isotypic_symmetry=True,
            auto_orbits=True,
        )
    with pytest.raises(ValueError, match="orbit_method must be"):
        GraphKoopmanOperator(
            2,
            init_mode="identity",
            auto_orbits=True,
            orbit_method="wl",  # type: ignore[arg-type]
        )

    pending = GraphKoopmanOperator(2, init_mode="identity", auto_orbits=True)
    with pytest.raises(ValueError, match="edge_index or hyperedge_index"):
        pending.bind_auto_orbits(num_nodes=2)
    with pytest.raises(RuntimeError, match="orbit self bank is not allocated"):
        pending.orbit_self_matrices()

    bound = GraphKoopmanOperator(
        2,
        init_mode="identity",
        orbit_partition=((0,), (1,)),
    )
    with pytest.raises(ValueError, match="orbit partition was bound for 2 nodes"):
        bound.ensure_orbit_binding(3)


# ---------------------------------------------------------------------------
# nn.sheaf
# ---------------------------------------------------------------------------


def test_sheaf_construction_and_forward_guards() -> None:
    """Restriction-map / Data / feature-dim / stack-type guards."""
    from koopman_graph.nn.sheaf import (
        SheafConv,
        SheafGNNEncoder,
        build_sheaf_convs,
    )

    with pytest.raises(ValueError, match="restriction_maps must be"):
        SheafConv(4, 4, restriction_maps="laplacian")  # type: ignore[arg-type]
    layers = build_sheaf_convs(2, 4, 3, num_layers=1)
    assert len(layers) == 1

    encoder = SheafGNNEncoder(in_channels=2, hidden_channels=4, latent_dim=2)
    with pytest.raises(ValueError, match="data.edge_index is required"):
        encoder(Data(x=torch.randn(3, 2)))
    with pytest.raises(ValueError, match="edge_index is required when"):
        encoder(torch.randn(3, 2))
    with pytest.raises(ValueError, match="in_channels=2"):
        encoder(torch.randn(3, 5), torch.tensor([[0, 1], [1, 0]], dtype=torch.long))
    with pytest.raises(ValueError, match="Expected x with shape"):
        encoder(torch.randn(3), torch.tensor([[0, 1], [1, 0]], dtype=torch.long))

    encoder.convs[0] = torch.nn.Linear(2, 2)  # type: ignore[assignment]
    with pytest.raises(TypeError, match="expected SheafConv"):
        encoder(torch.randn(2, 2), torch.tensor([[0, 1], [1, 0]], dtype=torch.long))


# ---------------------------------------------------------------------------
# analysis.transfer / analysis.spectrum
# ---------------------------------------------------------------------------


def test_topology_transfer_and_implied_timescale_guards() -> None:
    """Easy evaluate_topology_transfer and implied_timescales input guards."""
    from koopman_graph.analysis import (
        evaluate_topology_transfer,
        implied_timescales,
    )

    with pytest.raises(TypeError, match="GraphKoopmanModel architecture template"):
        evaluate_topology_transfer(
            object(),  # type: ignore[arg-type]
            _tiny_sequence(),
            _tiny_sequence(),
            _tiny_sequence(),
            steps=1,
        )
    with pytest.raises(ValueError, match="steps must be >= 1"):
        evaluate_topology_transfer(
            _tiny_model(),
            _tiny_sequence(),
            _tiny_sequence(),
            _tiny_sequence(),
            steps=0,
        )
    with pytest.raises(ValueError, match="controls must be a non-empty"):
        evaluate_topology_transfer(
            _tiny_model(),
            _tiny_sequence(),
            _tiny_sequence(),
            _tiny_sequence(),
            controls=(),
            steps=1,
        )

    eigenvalues = torch.tensor([0.5], dtype=torch.float64)
    with pytest.raises(ValueError, match="magnitude_atol must be > 0"):
        implied_timescales(eigenvalues, lag_steps=1, magnitude_atol=0.0)
    with pytest.raises(ValueError, match="magnitude_atol must be < 0.5"):
        implied_timescales(eigenvalues, lag_steps=1, magnitude_atol=0.5)


# ---------------------------------------------------------------------------
# baselines.gnn AGCRN / MTGNN / GraphCast
# ---------------------------------------------------------------------------


def test_agcrn_mtgnn_graphcast_constructor_guards() -> None:
    """Constructor / set_num_nodes / teaching-mesh validation branches."""
    from koopman_graph.baselines.gnn import AGCRNBaseline, MTGNNBaseline
    from koopman_graph.baselines.gnn.graphcast import build_teaching_mesh_edge_index

    with pytest.raises(ValueError, match="embed_dim must be positive"):
        AGCRNBaseline(1, 4, 1, embed_dim=0)
    agcrn = AGCRNBaseline(1, 4, 1, embed_dim=2, num_nodes=3)
    with pytest.raises(ValueError, match="num_nodes must be positive"):
        agcrn.set_num_nodes(0)
    with pytest.raises(ValueError, match="node embeddings are static"):
        agcrn.set_num_nodes(4)

    with pytest.raises(ValueError, match="embed_dim must be positive"):
        MTGNNBaseline(1, 4, 1, embed_dim=0)
    with pytest.raises(ValueError, match="num_layers must be positive"):
        MTGNNBaseline(1, 4, 1, num_layers=0)
    mtgnn = MTGNNBaseline(1, 4, 1, embed_dim=2, num_layers=1, num_nodes=2)
    with pytest.raises(ValueError, match="node embeddings are static"):
        mtgnn.set_num_nodes(5)

    with pytest.raises(ValueError, match="teaching mesh requires"):
        build_teaching_mesh_edge_index(num_lat=1, num_lon=2)


# ---------------------------------------------------------------------------
# datasets.molecular.synthetic
# ---------------------------------------------------------------------------


def test_synthetic_two_state_generation_guards() -> None:
    """Length / noise / lag / transition-prob generation validators."""
    from koopman_graph.datasets.molecular import (
        generate_synthetic_two_state,
        synthetic_two_state_oracle_timescale,
    )

    with pytest.raises(ValueError, match="num_timesteps must be >= 2"):
        generate_synthetic_two_state(num_timesteps=1)
    with pytest.raises(ValueError, match="noise_std must be finite"):
        generate_synthetic_two_state(num_timesteps=4, noise_std=-0.1)
    with pytest.raises(ValueError, match="noise_std must be finite"):
        generate_synthetic_two_state(num_timesteps=4, noise_std=float("nan"))
    with pytest.raises(ValueError, match="transition_prob must be in"):
        generate_synthetic_two_state(num_timesteps=4, transition_prob=0.5)
    with pytest.raises(ValueError, match="lag_steps must be >= 1"):
        synthetic_two_state_oracle_timescale(0.05, lag_steps=0)


# ---------------------------------------------------------------------------
# data.containers / data.validation (presence masks)
# ---------------------------------------------------------------------------


def test_presence_mask_accessor_and_validation_guards() -> None:
    """Presence-mask dtype / accessor / pair-mask edge branches."""
    from koopman_graph.data.validation import validate_presence_masks

    with pytest.raises(ValueError, match="presence_masks must have shape"):
        validate_presence_masks(
            torch.ones(3, dtype=torch.bool),
            num_timesteps=3,
            num_nodes=2,
        )
    with pytest.raises(ValueError, match="boolean or numeric"):
        validate_presence_masks(
            torch.ones(2, 2, dtype=torch.complex64),
            num_timesteps=2,
            num_nodes=2,
        )

    edge = torch.tensor([[0, 1], [1, 0]], dtype=torch.long)
    snaps = [Data(x=torch.ones(2, 1), edge_index=edge) for _ in range(3)]
    presence = torch.ones(3, 2, dtype=torch.bool)
    presence[1, 0] = False
    sequence = GraphSnapshotSequence(
        snaps,
        presence_masks=presence,
        allow_node_churn=True,
    )
    with pytest.raises(ValueError, match="presence mask index"):
        sequence.presence_mask_at(3)
    with pytest.raises(ValueError, match="pair presence mask index"):
        sequence.pair_presence_mask(2)
    pair = sequence.pair_presence_mask(0)
    assert pair.shape == (2,)
    assert bool(pair[0].item()) is False


# ---------------------------------------------------------------------------
# model.inference.resolve_future_presence_at
# ---------------------------------------------------------------------------


def test_resolve_future_presence_at_guards() -> None:
    """Tensor / sequence shape and length guards for forecast presence."""
    from koopman_graph.model.inference import resolve_future_presence_at

    assert resolve_future_presence_at(None, steps=2, num_nodes=3) is None

    schedule = resolve_future_presence_at(
        torch.ones(2, 3, dtype=torch.bool),
        steps=2,
        num_nodes=3,
    )
    assert schedule is not None
    assert schedule(0).shape == (3,)

    with pytest.raises(ValueError, match="future_presence tensor must have shape"):
        resolve_future_presence_at(torch.ones(2, 2), steps=2, num_nodes=3)
    with pytest.raises(ValueError, match="future_presence length"):
        resolve_future_presence_at(
            [torch.ones(3, dtype=torch.bool)],
            steps=2,
            num_nodes=3,
        )
    with pytest.raises(ValueError, match=r"future_presence\[1\] must have shape"):
        resolve_future_presence_at(
            [torch.ones(3, dtype=torch.bool), torch.ones(2, dtype=torch.bool)],
            steps=2,
            num_nodes=3,
        )
