"""Tests for data-driven spectral residuals."""

from __future__ import annotations

import inspect
import math
from dataclasses import fields

import pytest
import torch
from tests.helpers import REPO_ROOT
from torch_geometric.data import Data

import koopman_graph.analysis as analysis
from koopman_graph import (
    GNNDecoder,
    GNNEncoder,
    GraphKoopmanModel,
    GraphSnapshotSequence,
    compute_spectrum,
)
from koopman_graph.analysis import (
    ResDMDReport,
    SpectralResidualReport,
    resdmd,
    spectral_residuals,
)
from koopman_graph.analysis import residuals as residuals_module
from koopman_graph.spectrum_types import KoopmanSpectrum

_RESIDUALS_PATH = REPO_ROOT / "src" / "koopman_graph" / "analysis" / "residuals.py"


def _path_edges(num_nodes: int) -> torch.Tensor:
    """Build an undirected path ``edge_index``."""
    sources = list(range(num_nodes - 1)) + list(range(1, num_nodes))
    targets = list(range(1, num_nodes)) + list(range(num_nodes - 1))
    return torch.tensor([sources, targets], dtype=torch.long)


def _identity_encoder_decoder(
    feature_dim: int,
    latent_dim: int,
) -> tuple[GNNEncoder, GNNDecoder]:
    """Build encoder/decoder with near-identity linear maps for synthetic tests."""
    encoder = GNNEncoder(feature_dim, latent_dim, latent_dim, num_layers=1)
    decoder = GNNDecoder(latent_dim, feature_dim, feature_dim, num_layers=1)
    with torch.no_grad():
        for module in (encoder, decoder):
            for parameter in module.parameters():
                if parameter.ndim == 2 and parameter.shape[0] == parameter.shape[1]:
                    eye = torch.eye(parameter.shape[0], dtype=parameter.dtype)
                    parameter.copy_(eye)
                elif parameter.ndim == 1:
                    parameter.zero_()
                elif parameter.ndim == 2:
                    # Rectangular: pad / truncate identity.
                    eye = torch.zeros_like(parameter)
                    rank = min(parameter.shape)
                    eye[:rank, :rank] = torch.eye(rank, dtype=parameter.dtype)
                    parameter.copy_(eye)
    return encoder, decoder


def _rollout_features(
    initial: torch.Tensor,
    operator: torch.Tensor,
    steps: int,
) -> list[torch.Tensor]:
    """Apply a shared per-node linear map for ``steps`` transitions."""
    states = [initial]
    state = initial
    for _ in range(steps):
        state = state @ operator.T
        states.append(state)
    return states


def _sequence_from_features(
    features: list[torch.Tensor],
    edge_index: torch.Tensor,
) -> GraphSnapshotSequence:
    """Wrap feature frames as a static-topology snapshot sequence."""
    snapshots = [
        Data(x=frame.clone(), edge_index=edge_index.clone()) for frame in features
    ]
    return GraphSnapshotSequence(snapshots)


def test_exact_linear_system_residuals_near_zero() -> None:
    """Residuals vanish for data generated by the claimed discrete operator."""
    torch.manual_seed(0)
    latent_dim = 3
    num_nodes = 4
    edge_index = _path_edges(num_nodes)
    operator = torch.diag(torch.tensor([0.9, 0.7, 0.5], dtype=torch.float64))
    encoder, decoder = _identity_encoder_decoder(latent_dim, latent_dim)
    model = GraphKoopmanModel(
        encoder=encoder,
        decoder=decoder,
        latent_dim=latent_dim,
        time_step=1.0,
        koopman_init_mode="identity",
    )
    with torch.no_grad():
        model.koopman.K.copy_(operator.to(model.koopman.K.dtype))

    initial = torch.randn(num_nodes, latent_dim, dtype=torch.float64)
    features = _rollout_features(initial, operator, steps=12)
    # Cast to model dtype for encode path.
    features = [frame.to(dtype=torch.float32) for frame in features]
    sequence = _sequence_from_features(features, edge_index)

    report = spectral_residuals(model, sequence, tolerance=1e-2)
    assert isinstance(report, SpectralResidualReport)
    assert report.num_pairs == 12
    assert report.residuals.shape == (latent_dim,)
    assert torch.all(report.residuals >= 0)
    assert torch.all(torch.isfinite(report.residuals))
    # Near-identity encoder + exact linear data → residuals at float tolerance.
    assert torch.all(report.residuals < 5e-2)
    assert torch.all(report.trustworthy_mask())


def test_wrong_eigenvalue_residual_dominates_true_modes() -> None:
    """Wrong λ on a true eigenbasis → large residual (rejects matrix residual).

    The vacuous matrix residual ``\\|Kv - λv\\| / \\|v\\|`` after
    ``torch.linalg.eig`` is machine epsilon for every eigenpair of ``K`` and
    cannot detect eigenvalues that fail to propagate on data. Here the
    eigenvectors are exact for the data-generating operator, but one
    eigenvalue is replaced by a junk claim; the data-driven residual for that
    mode must be large while true-mode residuals stay small.
    """
    torch.manual_seed(1)
    latent_dim = 3
    num_nodes = 5
    edge_index = _path_edges(num_nodes)
    operator = torch.diag(torch.tensor([0.9, 0.7, 0.5], dtype=torch.float64))
    encoder, decoder = _identity_encoder_decoder(latent_dim, latent_dim)
    model = GraphKoopmanModel(
        encoder=encoder,
        decoder=decoder,
        latent_dim=latent_dim,
        time_step=1.0,
        koopman_init_mode="identity",
    )
    with torch.no_grad():
        model.koopman.K.copy_(operator.to(model.koopman.K.dtype))

    initial = torch.randn(num_nodes, latent_dim, dtype=torch.float64)
    features = [
        frame.to(dtype=torch.float32)
        for frame in _rollout_features(initial, operator, steps=20)
    ]
    sequence = _sequence_from_features(features, edge_index)

    true_spectrum = compute_spectrum(operator, time_step=1.0)
    # Vacuous matrix residual is ~0 for every eigenpair of K.
    complex_k = operator.to(dtype=true_spectrum.eigenvectors.dtype)
    matrix_residual = torch.linalg.vector_norm(
        complex_k @ true_spectrum.eigenvectors
        - true_spectrum.eigenvectors * true_spectrum.eigenvalues,
        dim=0,
    ) / torch.linalg.vector_norm(true_spectrum.eigenvectors, dim=0).clamp_min(1e-12)
    assert torch.all(matrix_residual < 1e-10)

    true_report = spectral_residuals(
        model,
        sequence,
        spectrum=true_spectrum,
        tolerance=1e-2,
    )

    # Keep true eigenvectors; claim a junk eigenvalue for the slowest mode.
    junk_eigenvalues = true_spectrum.eigenvalues.clone()
    junk_eigenvalues[-1] = -0.3 + 0.0j
    junk_spectrum = KoopmanSpectrum(
        eigenvalues=junk_eigenvalues,
        eigenvectors=true_spectrum.eigenvectors.clone(),
        magnitudes=junk_eigenvalues.abs(),
        growth_rates=true_spectrum.growth_rates.clone(),
        frequencies=true_spectrum.frequencies.clone(),
        time_step=true_spectrum.time_step,
    )
    junk_report = spectral_residuals(
        model,
        sequence,
        spectrum=junk_spectrum,
        tolerance=1e-2,
    )

    true_max = float(true_report.residuals.max().item())
    junk_mode = float(junk_report.residuals[-1].item())
    # |λ_true - λ_junk| ≈ |0.5 - (-0.3)| = 0.8 for a pure eigenmode trajectory.
    assert junk_mode > 10.0 * max(true_max, 1e-6)
    assert junk_mode > 0.5
    assert not bool(junk_report.trustworthy_mask()[-1].item())


def test_complex_eigenpairs_yield_real_finite_residuals() -> None:
    """Complex conjugate modes produce real, finite, non-negative residuals."""
    torch.manual_seed(2)
    radius = 0.9
    angle = math.pi / 5
    operator = torch.tensor(
        [
            [radius * math.cos(angle), -radius * math.sin(angle), 0.0],
            [radius * math.sin(angle), radius * math.cos(angle), 0.0],
            [0.0, 0.0, 0.55],
        ],
        dtype=torch.float64,
    )
    latent_dim = 3
    num_nodes = 3
    edge_index = _path_edges(num_nodes)
    encoder, decoder = _identity_encoder_decoder(latent_dim, latent_dim)
    model = GraphKoopmanModel(
        encoder=encoder,
        decoder=decoder,
        latent_dim=latent_dim,
        time_step=0.5,
        koopman_init_mode="identity",
    )
    with torch.no_grad():
        model.koopman.K.copy_(operator.to(model.koopman.K.dtype))

    initial = torch.randn(num_nodes, latent_dim, dtype=torch.float64)
    features = [
        frame.to(dtype=torch.float32)
        for frame in _rollout_features(initial, operator, steps=15)
    ]
    sequence = _sequence_from_features(features, edge_index)
    report = spectral_residuals(model, sequence)
    assert report.residuals.dtype == torch.float64
    assert torch.all(report.residuals >= 0)
    assert torch.all(torch.isfinite(report.residuals))
    assert report.eigenvalues.is_complex()


def test_trustworthy_mask_respects_tolerance() -> None:
    """Boundary: residual == tolerance is trustworthy; above is not."""
    report = SpectralResidualReport(
        eigenvalues=torch.tensor([0.5 + 0j, 0.3 + 0j]),
        residuals=torch.tensor([1e-2, 1e-2 + 1e-9], dtype=torch.float64),
        num_pairs=4,
        tolerance=1e-2,
    )
    mask = report.trustworthy_mask()
    assert bool(mask[0].item())
    assert not bool(mask[1].item())


def test_graph_koopman_residuals_run() -> None:
    """Networked ``koopman='graph'`` resolves topology and returns finite residuals."""
    torch.manual_seed(3)
    num_nodes = 4
    latent_dim = 2
    edge_index = _path_edges(num_nodes)
    model = GraphKoopmanModel(
        encoder=GNNEncoder(2, 8, latent_dim),
        decoder=GNNDecoder(latent_dim, 8, 2),
        latent_dim=latent_dim,
        koopman="graph",
        time_step=1.0,
    )
    features = [torch.randn(num_nodes, 2, dtype=torch.float32) for _ in range(8)]
    sequence = _sequence_from_features(features, edge_index)
    report = spectral_residuals(model, sequence, tolerance=1.0)
    assert report.residuals.shape == (num_nodes * latent_dim,)
    assert torch.all(torch.isfinite(report.residuals))
    assert report.num_pairs == 7


def test_continuous_uses_discrete_delta_t_spectrum() -> None:
    """Continuous models evaluate residuals via discrete spectrum at ``delta_t``."""
    torch.manual_seed(4)
    latent_dim = 2
    num_nodes = 3
    edge_index = _path_edges(num_nodes)
    # Generator with known decay rates; discrete map is exp(L Δt).
    generator = torch.diag(torch.tensor([-0.2, -0.5], dtype=torch.float64))
    delta_t = 0.25
    discrete = torch.linalg.matrix_exp(generator * delta_t)
    encoder, decoder = _identity_encoder_decoder(latent_dim, latent_dim)
    model = GraphKoopmanModel(
        encoder=encoder,
        decoder=decoder,
        latent_dim=latent_dim,
        dynamics_mode="continuous",
        time_step=delta_t,
        koopman_init_mode="identity",
    )
    with torch.no_grad():
        model.koopman.L.copy_(generator.to(model.koopman.L.dtype))

    initial = torch.randn(num_nodes, latent_dim, dtype=torch.float64)
    features = [
        frame.to(dtype=torch.float32)
        for frame in _rollout_features(initial, discrete, steps=10)
    ]
    sequence = _sequence_from_features(features, edge_index)
    report = spectral_residuals(model, sequence, delta_t=delta_t, tolerance=1e-2)
    assert report.num_pairs == 10
    assert torch.all(report.residuals < 5e-2)


def test_rejects_short_sequence_and_nonpositive_tolerance() -> None:
    """Input validation for short sequences and invalid tolerance."""
    edge_index = _path_edges(2)
    model = GraphKoopmanModel(
        encoder=GNNEncoder(1, 4, 2),
        decoder=GNNDecoder(2, 4, 1),
        latent_dim=2,
        time_step=1.0,
    )
    short = GraphSnapshotSequence([Data(x=torch.randn(2, 1), edge_index=edge_index)])
    with pytest.raises(ValueError, match="at least two snapshots"):
        spectral_residuals(model, short)
    sequence = GraphSnapshotSequence(
        [
            Data(x=torch.randn(2, 1), edge_index=edge_index),
            Data(x=torch.randn(2, 1), edge_index=edge_index),
        ]
    )
    with pytest.raises(ValueError, match="tolerance must be positive"):
        spectral_residuals(model, sequence, tolerance=0.0)


def test_not_exported_from_root_all() -> None:
    """Capability-module import only; not on the root façade."""
    import koopman_graph

    assert "spectral_residuals" not in koopman_graph.__all__
    assert "SpectralResidualReport" not in koopman_graph.__all__


def test_spectral_residuals_api_signature_stable() -> None:
    """Public signature and report fields remain stable (TASK-1837)."""
    params = inspect.signature(spectral_residuals).parameters
    for name in (
        "model",
        "sequence",
        "spectrum",
        "tolerance",
        "edge_index",
        "edge_weight",
        "delta_t",
    ):
        assert name in params
    field_names = {f.name for f in fields(SpectralResidualReport)}
    assert field_names == {
        "eigenvalues",
        "residuals",
        "num_pairs",
        "tolerance",
    }
    assert callable(SpectralResidualReport.trustworthy_mask)


def test_spectral_residuals_not_aliased_to_resdmd() -> None:
    """ResDMD and spectral_residuals stay distinct symbols (R2)."""
    assert spectral_residuals is not resdmd
    assert SpectralResidualReport is not ResDMDReport
    assert analysis.spectral_residuals is residuals_module.spectral_residuals
    assert analysis.spectral_residuals is not resdmd
    assert analysis.SpectralResidualReport is not ResDMDReport
    required = {
        "spectral_residuals",
        "SpectralResidualReport",
        "resdmd",
        "ResDMDReport",
    }
    assert required.issubset(set(analysis.__all__))


def test_spectral_residuals_honesty_docs_separate_resdmd() -> None:
    """Docs forbid renaming/aliasing spectral_residuals as ResDMD."""
    source = _RESIDUALS_PATH.read_text(encoding="utf-8")
    doc = (spectral_residuals.__doc__ or "") + source
    assert "ResDMD" in doc
    assert "not" in doc.lower()
    assert "rename" in doc.lower() or "alias" in doc.lower()
    assert "from koopman_graph.analysis.resdmd" not in source
    assert "import koopman_graph.analysis.resdmd" not in source
