"""Innovation-whiteness diagnostic and finite-memory convolution tests."""

from __future__ import annotations

import ast
from pathlib import Path

import pytest
import torch
from torch import nn

import koopman_graph
import koopman_graph.analysis as analysis
from koopman_graph.analysis.memory import (
    DEFAULT_ALPHA,
    LAG_UNIT,
    FiniteMemoryKoopman,
    MarkovClosureReport,
    markov_closure_report,
)
from koopman_graph.model.factory import parse_koopman_arg
from koopman_graph.nn.delay import DelayEmbeddingEncoder

# Independent AR(2) construction: residual energy of a known memory tap.
_ORACLE_REL = 1e-6
_ORACLE_ABS = 1e-8
_SERIES_LEN = 512
_MAX_LAG = 8
_LATENT_DIM = 2
_MEMORY_ORDER = 1
_SEED = 0
# 4 / sqrt(T) is a conservative envelope on |ρ̂| for i.i.d. N(0, 1).
_WHITE_ACF_BOUND = 4.0 / (_SERIES_LEN**0.5)
# Colored residuals of the hidden-memory oracle reject far below 5%.
_COLORED_P_CEILING = 1e-8
# Negative-control α is loose so a 5% portmanteau false reject cannot flake.
_WHITE_ALPHA = 1e-4


def _hidden_memory_trajectory() -> tuple[
    torch.Tensor, torch.Tensor, FiniteMemoryKoopman
]:
    """Latent AR(2) driven by a known convolution plus white noise.

    Returns
    -------
    tuple[Tensor, Tensor, FiniteMemoryKoopman]
        Latents ``(T, d)``, injected noise ``(T - 1, d)``, and the
        operator that generated the Markov-plus-memory step.
    """
    torch.manual_seed(_SEED)
    operator = FiniteMemoryKoopman(
        latent_dim=_LATENT_DIM,
        memory_order=_MEMORY_ORDER,
    )
    with torch.no_grad():
        operator.omega.copy_(0.5 * torch.eye(_LATENT_DIM))
        operator.kernels.copy_(0.35 * torch.eye(_LATENT_DIM).unsqueeze(0))
    noise = 0.15 * torch.randn(_SERIES_LEN - 1, _LATENT_DIM)
    latents = torch.zeros(_SERIES_LEN, _LATENT_DIM)
    latents[0] = torch.randn(_LATENT_DIM)
    for step in range(_SERIES_LEN - 1):
        if step == 0:
            history = latents[0].unsqueeze(0)
        else:
            history = latents[step - 1].unsqueeze(0)
        latents[step + 1] = operator.advance(latents[step], history) + noise[step]
    return latents, noise, operator


def test_package_and_analysis_export_memory_off_root() -> None:
    """Memory helpers live on ``analysis.__all__``, not the root façade."""
    assert "markov_closure_report" in analysis.__all__
    assert "MarkovClosureReport" in analysis.__all__
    assert "FiniteMemoryKoopman" in analysis.__all__
    assert "markov_closure_report" not in koopman_graph.__all__
    assert "FiniteMemoryKoopman" not in koopman_graph.__all__
    assert analysis.markov_closure_report is markov_closure_report
    assert analysis.FiniteMemoryKoopman is FiniteMemoryKoopman


def test_memory_module_does_not_import_model() -> None:
    """L2 analysis helper must not import L4 model."""
    source = Path(__file__).resolve().parents[2] / (
        "src/koopman_graph/analysis/memory.py"
    )
    tree = ast.parse(source.read_text(encoding="utf-8"))
    imported: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported.extend(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module is not None:
            imported.append(node.module)
    offenders = [
        name
        for name in imported
        if name == "koopman_graph.model" or name.startswith("koopman_graph.model.")
    ]
    assert not offenders


def test_white_innovations_do_not_flag_markov_mismatch() -> None:
    """i.i.d. residual energy fails to reject whiteness at a loose α."""
    torch.manual_seed(_SEED)
    innovations = torch.randn(_SERIES_LEN)
    report = markov_closure_report(
        innovations,
        max_lag=_MAX_LAG,
        alpha=_WHITE_ALPHA,
    )
    assert report.white
    assert report.lag_unit == LAG_UNIT
    assert report.max_lag == _MAX_LAG
    assert report.n_timesteps == _SERIES_LEN
    assert report.max_abs_autocorrelation < _WHITE_ACF_BOUND
    assert report.ljung_box_pvalue > _WHITE_ALPHA


def test_hidden_memory_oracle_flags_markov_mismatch() -> None:
    """Markov residuals of an AR(2) latent fail the whiteness flag.

    The process is generated by :class:`FiniteMemoryKoopman` plus white
    noise. Subtracting only the Markov term leaves the memory tap in
    the residual, so Ljung–Box must reject. Injected noise is the
    negative control.
    """
    latents, noise, operator = _hidden_memory_trajectory()
    markov_residuals = latents[1:] - latents[:-1] @ operator.omega.detach().T
    colored = markov_closure_report(
        markov_residuals,
        max_lag=_MAX_LAG,
        alpha=DEFAULT_ALPHA,
    )
    white = markov_closure_report(
        noise,
        max_lag=_MAX_LAG,
        alpha=_WHITE_ALPHA,
    )
    assert colored.white is False
    assert colored.ljung_box_pvalue < _COLORED_P_CEILING
    assert white.white is True
    assert white.ljung_box_pvalue > colored.ljung_box_pvalue
    assert colored.max_abs_autocorrelation > white.max_abs_autocorrelation


def test_convolution_matches_independent_ar2_step() -> None:
    """One step equals ``z Ωᵀ + z_{t-1} K₁ᵀ`` at tight float64 tolerance."""
    operator = FiniteMemoryKoopman(latent_dim=3, memory_order=1).double()
    with torch.no_grad():
        operator.omega.copy_(
            torch.diag(torch.tensor([0.4, -0.2, 0.1], dtype=torch.float64))
        )
        operator.kernels.copy_(
            torch.diag(
                torch.tensor([0.25, 0.15, -0.05], dtype=torch.float64)
            ).unsqueeze(0)
        )
    current = torch.tensor([[1.0, -0.5, 0.25], [0.0, 0.75, -1.0]], dtype=torch.float64)
    previous = torch.tensor([[0.5, 0.0, 1.0], [-0.25, 0.5, 0.0]], dtype=torch.float64)
    expected = (
        current @ operator.omega.detach().T + previous @ operator.kernels.detach()[0].T
    )
    got = operator.advance(current, previous.unsqueeze(0))
    torch.testing.assert_close(got, expected, rtol=_ORACLE_REL, atol=_ORACLE_ABS)
    torch.testing.assert_close(
        operator(current, previous.unsqueeze(0)),
        expected,
        rtol=_ORACLE_REL,
        atol=_ORACLE_ABS,
    )


def test_delay_encoder_matched_width_is_not_memory() -> None:
    """Matched latent width does not make delay embedding a memory kernel."""

    class _TinyEncoder(nn.Module):
        def __init__(self) -> None:
            super().__init__()
            self.in_channels = 6
            self.latent_dim = 4

        def forward(
            self,
            x: torch.Tensor,
            edge_index: torch.Tensor,
            edge_weight: torch.Tensor | None = None,
        ) -> torch.Tensor:
            del edge_index, edge_weight
            return x.new_zeros(x.size(0), self.latent_dim)

    delay = DelayEmbeddingEncoder(_TinyEncoder(), n_delays=2)
    memory = FiniteMemoryKoopman(latent_dim=4, memory_order=2)
    assert delay.latent_dim == memory.latent_dim
    assert delay.in_channels == delay.n_delays * delay.feature_dim
    assert memory.kernels.shape == (2, 4, 4)
    with pytest.raises(ValueError, match="finite_memory"):
        parse_koopman_arg("finite_memory")


def test_report_and_operator_reject_invalid_inputs() -> None:
    """Boundary validation names the broken constraint."""
    series = torch.randn(40)
    with pytest.raises(ValueError, match="nonempty"):
        markov_closure_report(torch.empty(0))
    with pytest.raises(ValueError, match="finite"):
        markov_closure_report(torch.tensor([1.0, float("nan"), 0.0]))
    with pytest.raises(ValueError, match="real"):
        markov_closure_report(torch.ones(8, dtype=torch.complex64))
    with pytest.raises(ValueError, match="positive residual energy"):
        markov_closure_report(torch.ones(20))
    with pytest.raises(ValueError, match="alpha"):
        markov_closure_report(series, alpha=0.0)
    with pytest.raises(ValueError, match="max_lag"):
        markov_closure_report(series, max_lag=0)
    with pytest.raises(ValueError, match="n_timesteps must exceed"):
        markov_closure_report(series[:5], max_lag=8)
    with pytest.raises(ValueError, match="n_fit_parameters"):
        markov_closure_report(series, max_lag=4, n_fit_parameters=4)
    with pytest.raises(ValueError, match="latent_dim"):
        FiniteMemoryKoopman(latent_dim=0)
    with pytest.raises(ValueError, match="memory_order"):
        FiniteMemoryKoopman(latent_dim=2, memory_order=0)
    operator = FiniteMemoryKoopman(latent_dim=2, memory_order=1)
    z = torch.ones(3, 2)
    with pytest.raises(ValueError, match="history"):
        operator.advance(z, torch.ones(1, 2))
    with pytest.raises(ValueError, match="trailing dimension"):
        operator.advance(torch.ones(3, 3), torch.ones(1, 3, 3))
    with pytest.raises(ValueError, match="lag_unit"):
        MarkovClosureReport(
            autocorrelation=torch.zeros(2),
            ljung_box_statistic=1.0,
            ljung_box_pvalue=0.5,
            max_abs_autocorrelation=0.1,
            max_lag=2,
            n_timesteps=20,
            n_fit_parameters=0,
            alpha=0.05,
            white=True,
            lag_unit="second",
        )
